namespace PokemonGo.RocketAPI
{
	/// <summary>
	/// A Translator Made By Oktm.
	/// </summary>
	public static class ConvertPokemonName
	{

		/// <summary>
		/// 日本語に変換します。
		/// </summary>
		/// <param name="english_name"></param>
		/// <returns></returns>
		public static string ToJapanese(string english_name)
		{
			var i = 0;
			var jp_name = "";

			foreach (var en in Pokemons_EnglishNames)
			{
				if (en == english_name.ToUpper())
				{
					jp_name = Pokemons_JapaneseNames[i];
					break;
				}

				i++;
			}

			return jp_name;
		}

		/// <summary>
		/// Convert to English from Japanese.
		/// </summary>
		/// <param name="english_name"></param>
		/// <returns></returns>
		public static string ToEnglish(string japanese_name)
		{
			var i = 0;
			var en_name = "";

			foreach (var jp in Pokemons_JapaneseNames)
			{
				if (jp == japanese_name.ToUpper())
				{
					en_name = Pokemons_EnglishNames[i];
					break;
				}

				i++;
			}

			return en_name;
		}

		/// <summary>
		/// Il est converti en français.
		/// </summary>
		/// <param name="english_name"></param>
		/// <returns></returns>
		public static string ToFrench(string english_name)
		{
			var i = 0;
			var fr_name = "";

			foreach (var en in Pokemons_EnglishNames)
			{
				if (en == english_name.ToUpper())
				{
					fr_name = Pokemons_FrenchNames[i];
					break;
				}

				i++;
			}

			return fr_name;
		}

		#region Pokemons_EnglishNames
		public static string[] Pokemons_EnglishNames = new string[]
		{
			"MISSINGNO",
			"BULBASAUR",
			"IVYSAUR",
			"VENUSAUR",
			"CHARMANDER",
			"CHARMELEON",
			"CHARIZARD",
			"SQUIRTLE",
			"WARTORTLE",
			"BLASTOISE",
			"CATERPIE",
			"METAPOD",
			"BUTTERFREE",
			"WEEDLE",
			"KAKUNA",
			"BEEDRILL",
			"PIDGEY",
			"PIDGEOTTO",
			"PIDGEOT",
			"RATTATA",
			"RATICATE",
			"SPEAROW",
			"FEAROW",
			"EKANS",
			"ARBOK",
			"PIKACHU",
			"RAICHU",
			"SANDSHREW",
			"SANDSLASH",
			"NIDORAN_FEMALE",
			"NIDORINA",
			"NIDOQUEEN",
			"NIDORAN_MALE",
			"NIDORINO",
			"NIDOKING",
			"CLEFAIRY",
			"CLEFABLE",
			"VULPIX",
			"NINETALES",
			"JIGGLYPUFF",
			"WIGGLYTUFF",
			"ZUBAT",
			"GOLBAT",
			"ODDISH",
			"GLOOM",
			"VILEPLUME",
			"PARAS",
			"PARASECT",
			"VENONAT",
			"VENOMOTH",
			"DIGLETT",
			"DUGTRIO",
			"MEOWTH",
			"PERSIAN",
			"PSYDUCK",
			"GOLDUCK",
			"MANKEY",
			"PRIMEAPE",
			"GROWLITHE",
			"ARCANINE",
			"POLIWAG",
			"POLIWHIRL",
			"POLIWRATH",
			"ABRA",
			"KADABRA",
			"ALAKAZAM",
			"MACHOP",
			"MACHOKE",
			"MACHAMP",
			"BELLSPROUT",
			"WEEPINBELL",
			"VICTREEBEL",
			"TENTACOOL",
			"TENTACRUEL",
			"GEODUDE",
			"GRAVELER",
			"GOLEM",
			"PONYTA",
			"RAPIDASH",
			"SLOWPOKE",
			"SLOWBRO",
			"MAGNEMITE",
			"MAGNETON",
			"FARFETCHD",
			"DODUO",
			"DODRIO",
			"SEEL",
			"DEWGONG",
			"GRIMER",
			"MUK",
			"SHELLDER",
			"CLOYSTER",
			"GASTLY",
			"HAUNTER",
			"GENGAR",
			"ONIX",
			"DROWZEE",
			"HYPNO",
			"KRABBY",
			"KINGLER",
			"VOLTORB",
			"ELECTRODE",
			"EXEGGCUTE",
			"EXEGGUTOR",
			"CUBONE",
			"MAROWAK",
			"HITMONLEE",
			"HITMONCHAN",
			"LICKITUNG",
			"KOFFING",
			"WEEZING",
			"RHYHORN",
			"RHYDON",
			"CHANSEY",
			"TANGELA",
			"KANGASKHAN",
			"HORSEA",
			"SEADRA",
			"GOLDEEN",
			"SEAKING",
			"STARYU",
			"STARMIE",
			"MR_MIME",
			"SCYTHER",
			"JYNX",
			"ELECTABUZZ",
			"MAGMAR",
			"PINSIR",
			"TAUROS",
			"MAGIKARP",
			"GYARADOS",
			"LAPRAS",
			"DITTO",
			"EEVEE",
			"VAPOREON",
			"JOLTEON",
			"FLAREON",
			"PORYGON",
			"OMANYTE",
			"OMASTAR",
			"KABUTO",
			"KABUTOPS",
			"AERODACTYL",
			"SNORLAX",
			"ARTICUNO",
			"ZAPDOS",
			"MOLTRES",
			"DRATINI",
			"DRAGONAIR",
			"DRAGONITE",
			"MEWTWO",
			"MEW"
		};
		#endregion

		#region Pokemons_FrenchNames
		public static string[] Pokemons_FrenchNames = new string[]
		{
			"manquant pas",
			"Bulbizarre",
			"Herbizarre",
			"Florizarre",
			"Salamèche",
			"Reptincel",
			"Dracaufeu",
			"Carapuce",
			"Carabaffe",
			"Tortank",
			"Chenipan",
			"Chrysacier",
			"Papilusion",
			"Aspicot",
			"Coconfort",
			"Dardargnan",
			"Roucool",
			"Roucoups",
			"Roucarnage",
			"Rattata",
			"Rattatac",
			"Piafabec",
			"Rapasdepic",
			"Abo",
			"Arbok",
			"Pikachu",
			"Raichu",
			"Sabelette",
			"Sablaireau",
			"NIDORAN_FEMALE",
			"Nidorina",
			"Nidoqueen",
			"NIDORAN_MALE",
			"Nidorino",
			"Nidoking",
			"Mélofée",
			"Mélodelfe",
			"Goupix",
			"Feunard",
			"Rondoudou",
			"Grodoudou",
			"Nosferapti",
			"Nosferalto",
			"Mystherbe",
			"Ortide",
			"Rafflesia",
			"Paras",
			"Parasect",
			"Mimitoss",
			"Aéromite",
			"Taupiqueur",
			"Triopikeur",
			"Miaouss",
			"Persian",
			"Psykokwak",
			"Akwakwak",
			"Férosinge",
			"Colossinge",
			"Caninos",
			"Arcanin",
			"Ptitard",
			"Têtarte",
			"Tartard",
			"Abra",
			"Kadabra",
			"Alakazam",
			"Machoc",
			"Machopeur",
			"Mackogneur",
			"Chétiflor",
			"Boustiflor",
			"Empiflor",
			"Tentacool",
			"Tentacruel",
			"Racaillou",
			"Gravalanch",
			"Grolem",
			"Ponyta",
			"Galopa",
			"Ramoloss",
			"Flagadoss",
			"Magnéti",
			"Magnéton",
			"FARFETCHD",
			"Doduo",
			"Dodrio",
			"Otaria",
			"Lamantine",
			"Tadmorv",
			"Grotadmorv",
			"Kokiyas",
			"Crustabri",
			"Fantominus",
			"Spectrum",
			"Ectoplasma",
			"Onix",
			"Soporifik",
			"Hypnomade",
			"Krabby",
			"Krabboss",
			"Voltorbe",
			"Électrode",
			"Noeunoeuf",
			"Noadkoko",
			"Osselait",
			"Ossatueur",
			"Kicklee",
			"Tygnon",
			"Excelangue",
			"Smogo",
			"Smogogo",
			"Rhinocorne",
			"Rhinoféros",
			"Leveinard",
			"Saquedeneu",
			"Kangourex",
			"Hypotrempe",
			"Hypocéan",
			"Poissirène",
			"Poissoroy",
			"Stari",
			"Staross",
			"MR_MIME",
			"Insécateur",
			"Lippoutou",
			"Élektek",
			"Magmar",
			"Scarabrute",
			"Tauros",
			"Magicarpe",
			"Léviator",
			"Lokhlass",
			"Métamorph",
			"Évoli",
			"Aquali",
			"Voltali",
			"Pyroli",
			"Porygon",
			"Amonita",
			"Amonistar",
			"Kabuto",
			"Kabutops",
			"Ptéra",
			"Ronflex",
			"Artikodin",
			"Électhor",
			"Sulfura",
			"Minidraco",
			"Draco",
			"Dracolosse",
			"Mewtwo",
			"Mew"
		};
		#endregion

		#region Pokemons_JapaneseNames
		public static string[] Pokemons_JapaneseNames = new string[]
		{
			"不明",
			"フシギダネ",
			"フシギソウ",
			"フシギバナ",
			"ヒトカゲ",
			"リザード",
			"リザードン",
			"ゼニガメ",
			"カメール",
			"カメックス",
			"キャタピー",
			"トランセル",
			"バタフリー",
			"ビードル",
			"コクーン",
			"スピアー",
			"ポッポ",
			"ピジョン",
			"ピジョット",
			"コラッタ",
			"ラッタ",
			"オニスズメ",
			"オニドリル",
			"アーボ",
			"アーボック",
			"ピカチュウ",
			"ライチュウ",
			"サンド",
			"サンドパン",
			"ニドラン♀",
			"ニドリーナ",
			"ニドクイン",
			"ニドラン♂",
			"ニドリーノ",
			"ニドキング",
			"ピッピ",
			"ピクシー",
			"ロコン",
			"キュウコン",
			"プリン",
			"プクリン",
			"ズバット",
			"ゴルバット",
			"ナゾノクサ",
			"クサイハナ",
			"ラフレシア",
			"パラス",
			"パラセクト",
			"コンパン",
			"モルフォン",
			"ディグダ",
			"ダグトリオ",
			"ニャース",
			"ペルシアン",
			"コダック",
			"ゴルダック",
			"マンキー",
			"オコリザル",
			"ガーディ",
			"ウインディ",
			"ニョロモ",
			"ニョロゾ",
			"ニョロボン",
			"ケーシィ",
			"ユンゲラー",
			"フーディン",
			"ワンリキー",
			"ゴーリキー",
			"カイリキー",
			"マダツボミ",
			"ウツドン",
			"ウツボット",
			"メノクラゲ",
			"ドククラゲ",
			"イシツブテ",
			"ゴローン",
			"ゴローニャ",
			"ポニータ",
			"ギャロップ",
			"ヤドン",
			"ヤドラン",
			"コイル",
			"レアコイル",
			"カモネギ",
			"ドードー",
			"ドードリオ",
			"パウワウ",
			"ジュゴン",
			"ベトベター",
			"ベトベトン",
			"シェルダー",
			"パルシェン",
			"ゴース",
			"ゴースト",
			"ゲンガー",
			"イワーク",
			"スリープ",
			"スリーパー",
			"クラブ",
			"キングラー",
			"ビリリダマ",
			"マルマイン",
			"タマタマ",
			"ナッシー",
			"カラカラ",
			"ガラガラ",
			"サワムラー",
			"エビワラー",
			"ベロリンガ",
			"ドガース",
			"マタドガス",
			"サイホーン",
			"サイドン",
			"ラッキー",
			"モンジャラ",
			"ガルーラ",
			"タッツー",
			"シードラ",
			"トサキント",
			"アズマオウ",
			"ヒトデマン",
			"スターミー",
			"バリヤード",
			"ストライク",
			"ルージュラ",
			"エレブー",
			"ブーバー",
			"カイロス",
			"ケンタロス",
			"コイキング",
			"ギャラドス",
			"ラプラス",
			"メタモン",
			"イーブイ",
			"シャワーズ",
			"サンダース",
			"ブースター",
			"ポリゴン",
			"オムナイト",
			"オムスター",
			"カブト",
			"カブトプス",
			"プテラ",
			"カビゴン",
			"フリーザー",
			"サンダー",
			"ファイヤー",
			"ミニリュウ",
			"ハクリュー",
			"カイリュー",
			"ミュウツー",
			"ミュウ"
		};
		#endregion
	}
}